

def build(bld):
    bld.DefineGem(
        disable_pch = True,
        use = ['AzToolsFramework', 'AzQtComponents'],
        includes = 
        [
            bld.Path('Code/CryEngine/CryCommon'),
            bld.Path('Code/Sandbox'),
            'Source'
        ],
        uselib=['fastnoise'],

        Editor = dict(
            disable_pch = True,
            features = ['qt5', 'ExternalLyIdentity', 'ExternalLyMetrics'],

            defines             = ["EDITOR_MODULE"],
            uselib=['QT5CORE', 'QT5QUICK', 'QT5QML','QT5GUI', 'QT5WIDGETS'],
            includes =
            [
                bld.Path('Code/CryEngine/CryCommon'),
                bld.Path('Code/Sandbox'),
                bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                bld.Path('Code/Sandbox/Editor'),
                bld.Path('Code/Sandbox/Editor/Include'),
                'Source'
            ]
         )
    )
